# Generated by Django 4.2.26 on 2026-06-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('AGENT', '🟢 Normal Agent (ESC1)'), ('EXECUTIVE', '⚖️ Executive (ESC2)'), ('MANAGER', '📊 Manager (ESC3)'), ('HEAD', '👔 Head (ESC4)'), ('ADMIN', '🔒 Administrator (ESC5)')], default='AGENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_cases_handled', models.IntegerField(default=0)),
                ('total_cases_resolved', models.IntegerField(default=0)),
                ('total_escalations_made', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('source_app', models.CharField(choices=[('app1', 'App 1 - messaging'), ('app2', 'App 2 - messaging2'), ('app3', 'App 3 - splcase')], default='app12', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, to='adminpanel.supportgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BulkJob2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=100)),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=50)),
                ('excel_file', models.CharField(blank=True, default='', max_length=500)),
                ('success_report', models.FileField(blank=True, null=True, upload_to='reports2/')),
                ('failed_report', models.FileField(blank=True, null=True, upload_to='reports2/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('current_level', models.CharField(choices=[('ESC0', '🆕 New Case - Unassigned'), ('ESC1', '📞 Level 1 - Agent'), ('ESC2', '⭐ Level 2 - Executive'), ('ESC3', '📊 Level 3 - Manager'), ('ESC4', '👔 Level 4 - Head'), ('ESC5', '🔒 Level 5 - Admin'), ('RESOLVED', '✅ Resolved - Awaiting Closure'), ('CLOSED', '🔒 Closed - Final')], default='ESC0', max_length=20)),
                ('previous_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_at_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved - Pending Closure'), ('Closed', 'Closed - Final'), ('Reopened', 'Reopened')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', '🟢 Low'), ('Medium', '🟡 Medium'), ('High', '🟠 High'), ('Urgent', '🔴 Urgent')], default='Medium', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('reopen_count', models.IntegerField(default=0)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='WhatsApp', max_length=100, null=True)),
                ('source_app', models.CharField(choices=[('app1', 'App 1 - messaging'), ('app2', 'App 2 - messaging2'), ('app3', 'App 3 - splcase')], default='app1', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='messaging2.agent')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='adminpanel.supportgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsWhatsAppLog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('sent_text_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('message_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('content_type', models.CharField(blank=True, default='text', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='chat_media2/')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.IntegerField(blank=True, help_text='WhatsApp API error code', null=True)),
                ('error_reason', models.TextField(blank=True, help_text='Detailed error reason')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['mobile', '-sent_at'], name='messaging2__mobile_f37b02_idx'), models.Index(fields=['-sent_at'], name='messaging2__sent_at_30fe85_idx'), models.Index(fields=['message_type', 'status'], name='messaging2__message_4c7e18_idx'), models.Index(fields=['job_id'], name='messaging2__job_id_c054bf_idx'), models.Index(fields=['message_id'], name='messaging2__message_260ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatContact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_msg', models.TextField(blank=True, default='')),
                ('last_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_type', models.CharField(blank=True, default='', max_length=20)),
                ('last_status', models.CharField(blank=True, default='', max_length=500)),
                ('unread', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_level', models.CharField(blank=True, max_length=20, null=True)),
                ('current_level', models.CharField(blank=True, default='ESC1', max_length=20, null=True)),
            ],
            options={
                'ordering': ['-last_time'],
                'indexes': [models.Index(fields=['-last_time', 'unread'], name='messaging2__last_ti_c37491_idx'), models.Index(fields=['mobile'], name='messaging2__mobile_e78451_idx'), models.Index(fields=['assigned_to'], name='messaging2__assigne_b6f49d_idx'), models.Index(fields=['current_level'], name='messaging2__current_2894b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseEscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(max_length=20)),
                ('to_level', models.CharField(max_length=20)),
                ('escalated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='messaging2.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging2.agent')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging2.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='messaging2.agent')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='messaging2.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_id'], name='messaging2__case_id_6a85ef_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['mobile'], name='messaging2__mobile_7f0f06_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_level'], name='messaging2__current_8675de_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='messaging2__status_8655c8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='messaging2__priorit_838959_idx'),
        ),
    ]
