# Generated by Django 5.2.8 on 2025-11-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=50)),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('excel_file', models.FileField(upload_to='uploads2/')),
                ('success_report', models.FileField(blank=True, null=True, upload_to='reports2/')),
                ('failed_report', models.FileField(blank=True, null=True, upload_to='reports2/')),
            ],
        ),
        migrations.CreateModel(
            name='SmsWhatsAppLog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_text_message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received')], default='Sent', max_length=10)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('interactive', 'Interactive'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp2_media/')),
            ],
        ),
    ]
