# Generated by Django 4.2.26 on 2026-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontact2',
            name='last_status',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
