# Generated by Django 4.2.26 on 2026-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='source_app',
            field=models.CharField(choices=[('app1', 'App 1 - messaging'), ('app2', 'App 2 - messaging2'), ('app3', 'App 3 - splcase')], default='app2', max_length=20),
        ),
    ]
