# Generated by Django 4.2.26 on 2026-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0002_alter_bulkjob2_failed_report_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['mobile', 'sent_at'], name='messaging2__mobile_d1730b_idx'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['message_type', 'status'], name='messaging2__message_4c7e18_idx'),
        ),
    ]
