# Generated by Django 4.2.26 on 2026-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0002_alter_case_source_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='button_response',
            field=models.TextField(blank=True, default='', help_text='Store button click data as JSON'),
        ),
    ]
