# Generated by Django 4.2.26 on 2026-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0003_smswhatsapplog2_messaging2__mobile_d1730b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smswhatsapplog2',
            name='messaging2__mobile_d1730b_idx',
        ),
        migrations.RenameIndex(
            model_name='smswhatsapplog2',
            new_name='idx2_type_status',
            old_name='messaging2__message_4c7e18_idx',
        ),
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smswhatsapplog2',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smswhatsapplog2',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='bulkjob2',
            index=models.Index(fields=['job_id'], name='idx2_job_id'),
        ),
        migrations.AddIndex(
            model_name='bulkjob2',
            index=models.Index(fields=['status', 'started_at'], name='idx2_status_started'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['mobile', '-sent_at'], name='idx2_mobile_sent_at'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['message_id'], name='idx2_message_id'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['-sent_at'], name='idx2_sent_at_desc'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['mobile', 'message_type', 'status'], name='idx2_mobile_type_status'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['job_id', 'status'], name='idx2_job_status'),
        ),
    ]
