# Generated by Django 4.2.26 on 2026-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0003_agent_case_caseassignmentlog_casecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='error_code',
            field=models.IntegerField(blank=True, help_text='WhatsApp API error code', null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='error_reason',
            field=models.TextField(blank=True, help_text='Detailed error reason'),
        ),
    ]
