# Generated by Django 6.0.3 on 2026-06-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_subgroup'),
        ('messaging2', '0004_case_ticket_close_message_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='subgroup',
            field=models.ManyToManyField(blank=True, to='adminpanel.subgroup'),
        ),
        migrations.AddField(
            model_name='case',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcases', to='adminpanel.subgroup'),
        ),
    ]
