# Generated by Django 6.0.3 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0005_agent_subgroup_case_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_close',
            field=models.BooleanField(default=False, help_text='Can close resolved cases'),
        ),
        migrations.AddField(
            model_name='agent',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Can edit case metadata'),
        ),
        migrations.AddField(
            model_name='agent',
            name='can_resolve',
            field=models.BooleanField(default=False, help_text='Can resolve cases'),
        ),
    ]
