# Generated by Django 4.2.26 on 2026-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0008_alter_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_login',
            field=models.BooleanField(default=True, help_text='If unchecked, this user cannot log in.'),
        ),
    ]
