# Generated by Django 4.2.26 on 2026-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0013_smswhatsapplog2_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob2',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
