# Generated by Django 4.2.26 on 2026-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0015_case_alt_contact_case_customer_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob2',
            name='skipped_report',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports2/'),
        ),
    ]
