# Generated by Django 4.2.26 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0016_bulkjob2_skipped_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='due_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='emi_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='excel_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog2',
            index=models.Index(fields=['loan_number'], name='messaging2__loan_nu_7caf14_idx'),
        ),
    ]
