# Generated by Django 4.2.26 on 2026-09-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0010_batchlog_due_amount_batchlog_emi_count_and_more'),
        ('messaging2', '0017_smswhatsapplog2_due_amount_smswhatsapplog2_emi_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog2',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs2', to='batch_app.batchexecution'),
        ),
    ]
