# Generated by Django 4.2.26 on 2026-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0018_smswhatsapplog2_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
