# Generated by Django 4.2.26 on 2026-04-24 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=100)),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=50)),
                ('excel_file', models.CharField(blank=True, default='', max_length=500)),
                ('success_report', models.CharField(blank=True, default='', max_length=500)),
                ('failed_report', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('sent_text_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('message_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('content_type', models.CharField(blank=True, default='text', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='chat_media/')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['mobile', '-sent_at'], name='messaging_s_mobile_7c96e0_idx'), models.Index(fields=['-sent_at'], name='messaging_s_sent_at_e218dc_idx'), models.Index(fields=['message_type', 'status'], name='messaging_s_message_43f5c8_idx'), models.Index(fields=['job_id'], name='messaging_s_job_id_fb8e87_idx'), models.Index(fields=['message_id'], name='messaging_s_message_e181f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_msg', models.TextField(blank=True, default='')),
                ('last_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_type', models.CharField(blank=True, default='', max_length=20)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('unread', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_time'],
                'indexes': [models.Index(fields=['-last_time', 'unread'], name='messaging_c_last_ti_cec2d0_idx'), models.Index(fields=['mobile'], name='messaging_c_mobile_a749ec_idx')],
            },
        ),
    ]
