# Generated by Django 4.2.26 on 2026-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['processed', 'created_at'], name='messaging_p_process_1e71b7_idx')],
            },
        ),
    ]
