# Generated by Django 4.2.26 on 2025-12-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_repayment', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_number', models.CharField(db_index=True, max_length=150, unique=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('blc_cases', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_date', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('guarantor', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantor_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=255, null=True)),
                ('first_due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('last_due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('installment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('month_tbc', models.CharField(blank=True, max_length=100, null=True)),
                ('total_dues', models.CharField(blank=True, max_length=100, null=True)),
                ('lpc_dues', models.CharField(blank=True, max_length=100, null=True)),
                ('vas_hl', models.CharField(blank=True, max_length=100, null=True)),
                ('emi_due', models.CharField(blank=True, max_length=100, null=True)),
                ('emi_due_2', models.CharField(blank=True, max_length=100, null=True)),
                ('running_emi', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('inst', models.CharField(blank=True, max_length=100, null=True)),
                ('last_rcvd_date', models.CharField(blank=True, max_length=100, null=True)),
                ('seize_date', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('collection_executive', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_in_file', models.IntegerField(default=0)),
                ('rows_inserted', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
