# Generated by Django 4.2.26 on 2025-12-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=50)),
                ('LoanNO', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Dropdown', models.CharField(max_length=100)),
                ('feedback_dropdwon', models.CharField(choices=[('customer', 'Customer'), ('guarantor', 'Guarantor'), ('co-applicant', 'Co-applicant')], max_length=20)),
                ('PTPDate', models.DateField(blank=True, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
