# Generated by Django 4.2.26 on 2026-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clu',
            name='lpp_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
