# Generated by Django 4.2.26 on 2026-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clu',
            name='other_party_mobile_number',
        ),
        migrations.AddField(
            model_name='clu',
            name='bcc_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='net_other_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='other_party_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='total_penalty_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='ag_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='amount_paid_for_vehicle_release',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='days_bw_repossessed_and_released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='dist_bw_cust_addr_visit_addr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='dpd_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='emi_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='last_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='lpp_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='promised_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='ptp_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='time_spent_in_visit_location_in_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='total_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='vehicle_released_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='visited_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clu',
            name='workshop_outstanding_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
