# Generated by Django 4.2.26 on 2026-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0002_remove_clu_other_party_mobile_number_clu_bcc_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clu',
            name='visited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
