# Generated by Django 4.2.26 on 2025-12-03 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='executive_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='visiting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Dropdown',
            field=models.CharField(choices=[('PTP', 'PTP'), ('RTP', 'RTP'), ('WAIVER', 'WAIVER'), ('ACCIDENT', 'ACCIDENT'), ('PS/THEFT', 'PS/THEFT'), ('PLEDGE', 'PLEDGE'), ('THIRD PARTY', 'THIRD PARTY'), ('ADDRESS SHIFTED', 'ADDRESS SHIFTED'), ('NO RESPONSE / NOT TRACED', 'NO RESPONSE / NOT TRACED'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
