# Generated by Django 4.2.26 on 2025-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0003_feedback_executive_id_feedback_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_dropdwon',
            field=models.CharField(choices=[('customer', 'Customer'), ('guarantor', 'Guarantor'), ('co-applicant', 'Co-applicant'), ('others', 'Others')], max_length=20),
        ),
    ]
