# Generated by Django 4.2.26 on 2026-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0003_alter_clu_visited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clu',
            name='visited_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
