# Generated by Django 4.2.26 on 2025-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0004_feedback_customer_name_feedback_vehicle_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Dropdown',
            field=models.CharField(choices=[('PTP', 'PTP'), ('RTP', 'RTP'), ('WAIVER', 'WAIVER'), ('ACCIDENT', 'ACCIDENT'), ('PS/THEFT', 'PS/THEFT'), ('PLEDGE', 'PLEDGE'), ('THIRD PARTY', 'THIRD PARTY'), ('ADDRESS SHIFTED', 'ADDRESS SHIFTED'), ('NO RESPONSE / NOT TRACED', 'NO RESPONSE / NOT TRACED'), ('OTHERS', 'OTHERS'), ('WRONG NUMBER', 'Wrong Number'), ('BILLS NOT UPDATE', 'Bills Not Update'), ('NEW NUMBER', 'New Number')], max_length=100),
        ),
    ]
