# Generated by Django 4.2.26 on 2026-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0005_rename_time_difference_bw_prev_visit_clu_customer_lat_long_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='duenotice',
            name='duenotice_loan_nu_dd3fa4_idx',
        ),
        migrations.AddIndex(
            model_name='clu',
            index=models.Index(fields=['loan_number'], name='financehub__loan_nu_c24442_idx'),
        ),
        migrations.AddIndex(
            model_name='clu',
            index=models.Index(fields=['visited_on'], name='financehub__visited_a2114c_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionallocations',
            index=models.Index(fields=['loan_number'], name='Collection__loan_nu_f9ba60_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionallocations',
            index=models.Index(fields=['manager_employee_id'], name='Collection__manager_47cf57_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionallocations',
            index=models.Index(fields=['tl_employee_id'], name='Collection__tl_empl_d20005_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionallocations',
            index=models.Index(fields=['employee_id'], name='Collection__employe_b6b2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionallocations',
            index=models.Index(fields=['company'], name='Collection__company_65b1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='duenotice',
            index=models.Index(fields=['loan_number'], name='duenotice_loan_nu_80a030_idx'),
        ),
        migrations.AddIndex(
            model_name='duenotice',
            index=models.Index(fields=['type_of_notice'], name='duenotice_type_of_73390c_idx'),
        ),
        migrations.AddIndex(
            model_name='duenotice',
            index=models.Index(fields=['notice_date'], name='duenotice_notice__de8725_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['loan_number'], name='financehub__loan_nu_eb88ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['division'], name='financehub__divisio_5cab2b_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['branch'], name='financehub__branch_27f396_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['company'], name='financehub__company_2fecc5_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['blc_cases'], name='financehub__blc_cas_53820b_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['emi_due_2'], name='financehub__emi_due_001de0_idx'),
        ),
        migrations.AddIndex(
            model_name='lcc',
            index=models.Index(fields=['centre_name'], name='financehub__centre__645024_idx'),
        ),
        migrations.AddIndex(
            model_name='paid',
            index=models.Index(fields=['loan_number'], name='paid_loan_nu_c4a82a_idx'),
        ),
        migrations.AddIndex(
            model_name='paid',
            index=models.Index(fields=['received_date'], name='paid_receive_f2aaa1_idx'),
        ),
    ]
