# Generated by Django 4.2.26 on 2025-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0005_alter_feedback_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Dropdown',
            field=models.CharField(choices=[('PTP', 'PTP'), ('RTP', 'RTP'), ('WAIVER', 'WAIVER'), ('ACCIDENT', 'ACCIDENT'), ('PS/THEFT', 'PS/THEFT'), ('PLEDGE', 'PLEDGE'), ('THIRD PARTY', 'THIRD PARTY'), ('ADDRESS SHIFTED', 'ADDRESS SHIFTED'), ('NO RESPONSE / NOT TRACED', 'NO RESPONSE / NOT TRACED'), ('OTHERS', 'OTHERS'), ('WRONG NUMBER', 'Wrong Number'), ('BILLS NOT UPDATE', 'Bills Not Update'), ('NEW NUMBER', 'New Number'), ('REGISTRATION COMMITMENT', 'Registration Commitment'), ('TR SET ISSUE', 'Tr Set Issue'), ('SVT / HANDLOAN', 'SVT / Handloan'), ('REGISTRATION DONE', 'Registration Done'), ('WAITING FOR NUMBER', 'Waiting For Number'), ('PDD PENDING', 'Pdd Pending'), ('REGISTRATION ISSUE', 'Registration Issue')], max_length=100),
        ),
    ]
