# Generated by Django 4.2.26 on 2026-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0006_remove_duenotice_duenotice_loan_nu_dd3fa4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatusCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(db_index=True, max_length=150, unique=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loan_status_cache',
            },
        ),
    ]
