# Generated by Django 4.2.26 on 2026-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0007_loanstatuscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_count', models.IntegerField(default=0)),
                ('status_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'status_count_cache',
            },
        ),
    ]
