# Generated by Django 4.2.26 on 2025-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0007_closed_clu_collectionallocation_dialer_duenotice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadhistory',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='uploadhistory',
            old_name='rows_in_file',
            new_name='processed_rows',
        ),
        migrations.RenameField(
            model_name='uploadhistory',
            old_name='rows_inserted',
            new_name='total_rows',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
