# Generated by Django 4.2.26 on 2025-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0008_rename_error_uploadhistory_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='notice_period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
