# Generated by Django 4.2.26 on 2026-05-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0008_statuscountcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='finance_uploads',
            field=models.FileField(blank=True, null=True, upload_to='finance_uploads/'),
        ),
    ]
