# Generated by Django 4.2.26 on 2025-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0009_alter_employeemaster_notice_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='EseBuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanno', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('loantype', models.CharField(blank=True, max_length=255, null=True)),
                ('umrnno', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('postingdate', models.CharField(blank=True, max_length=100, null=True)),
                ('initiateddate', models.CharField(blank=True, max_length=100, null=True)),
                ('customername', models.CharField(blank=True, max_length=255, null=True)),
                ('bankaccountno', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsccode', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=100, null=True)),
                ('achtype', models.CharField(blank=True, max_length=100, null=True)),
                ('achagent', models.CharField(blank=True, max_length=255, null=True)),
                ('bankformat', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'esebuzz',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, max_length=100, null=True)),
                ('umrn', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('heroagreementno', models.CharField(blank=True, max_length=255, null=True)),
                ('referencenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('customername', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=100, null=True)),
                ('branchname', models.CharField(blank=True, max_length=255, null=True)),
                ('createdbyusername', models.CharField(blank=True, max_length=255, null=True)),
                ('createdbyemailid', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypttransheaderid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='KotakECS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loannumber', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('customername', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('ecsdate', models.CharField(blank=True, max_length=100, null=True)),
                ('ecsstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('releasestatus', models.CharField(blank=True, max_length=255, null=True)),
                ('released', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kotakecs',
            },
        ),
        migrations.CreateModel(
            name='Smsquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueregistrationnumber', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=255, null=True)),
                ('presentmentmode', models.CharField(blank=True, max_length=255, null=True)),
                ('customername', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('reasoncode', models.CharField(blank=True, max_length=100, null=True)),
                ('reasondescription', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'smsquare',
            },
        ),
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loannoreference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customername', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionamount', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('utrno', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofdeduction', models.CharField(blank=True, max_length=100, null=True)),
                ('amounttobededucted', models.CharField(blank=True, max_length=100, null=True)),
                ('initiateddatetime', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentdatetime', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentdescription', models.CharField(blank=True, max_length=500, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('notificationstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('payresponsecode', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=255, null=True)),
                ('accountno', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsccode', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upi',
            },
        ),
    ]
