# Generated by Django 4.2.26 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0009_uploadhistory_finance_uploads'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clu',
            constraint=models.UniqueConstraint(fields=('employee_id', 'visited_on'), name='unique_clu_employee_visit'),
        ),
    ]
