# Generated by Django 4.2.26 on 2025-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0010_esebuzz_hero_kotakecs_smsquare_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotakecs',
            name='released',
            field=models.TextField(blank=True, null=True),
        ),
    ]
