# Generated by Django 4.2.26 on 2026-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0010_clu_unique_clu_employee_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='suitcase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
