# Generated by Django 4.2.26 on 2025-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0011_alter_kotakecs_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveVisitScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanno', models.CharField(db_index=True, max_length=150)),
                ('visit_schedule_date', models.DateField()),
                ('empid', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'executive_visit_scheduling',
            },
        ),
    ]
