# Generated by Django 4.2.26 on 2025-12-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0012_executivevisitscheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivevisitscheduling',
            name='not_visited_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executivevisitscheduling',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executivevisitscheduling',
            name='visit_status',
            field=models.CharField(blank=True, choices=[('visited', 'Visited'), ('not_visited', 'Not Visited')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='executivevisitscheduling',
            name='empid',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
