# Generated by Django 4.2.26 on 2026-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0012_rename_achagent_esebuzz_ach_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsquare',
            table='smsquare_payments',
        ),
    ]
