# Generated by Django 4.2.26 on 2025-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0013_executivevisitscheduling_not_visited_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAllocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_number', models.CharField(db_index=True, max_length=150)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('tl', models.CharField(blank=True, max_length=255, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('tl_employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Collection_Allocations',
            },
        ),
    ]
