# Generated by Django 4.2.26 on 2026-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0013_alter_smsquare_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=225)),
                ('loan_number', models.CharField(max_length=225)),
                ('vehicle_number', models.CharField(db_index=True, max_length=225)),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
            ],
        ),
    ]
