# Generated by Django 4.2.26 on 2025-12-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0014_collectionallocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenotice',
            name='send_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
