# Generated by Django 4.2.26 on 2026-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0014_nocmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='coborrower_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcc',
            name='coborrower_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
