# Generated by Django 4.2.26 on 2026-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0015_lcc_coborrower_mobile_lcc_coborrower_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionallocations',
            name='previous_employee_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='collectionallocations',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
