# Generated by Django 4.2.26 on 2026-01-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0015_duenotice_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenotice',
            name='notice_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='duenotice',
            name='type_of_notice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lcc',
            name='installment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
