# Generated by Django 4.2.26 on 2026-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0016_collectionallocations_previous_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
