# Generated by Django 4.2.26 on 2026-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0016_duenotice_notice_status_duenotice_type_of_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenotice',
            name='notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esebuzz',
            name='initiateddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kotakecs',
            name='ecsdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsquare',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
