# Generated by Django 4.2.26 on 2026-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0017_employeemaster_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lcc',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
