# Generated by Django 4.2.26 on 2026-01-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0017_alter_duenotice_notice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenotice',
            name='notice_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('in_transit', 'In transit'), ('returned', 'Returned')], default='delivered', max_length=20),
        ),
        migrations.AddIndex(
            model_name='duenotice',
            index=models.Index(fields=['loan_number', 'bar_number', 'vehicle_no'], name='duenotice_loan_nu_dd3fa4_idx'),
        ),
    ]
