# Generated by Django 4.2.26 on 2026-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0018_lcc_chassis_number_lcc_engine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
