# Generated by Django 4.2.26 on 2026-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0018_alter_duenotice_notice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenotice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duenotice',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
