# Generated by Django 4.2.26 on 2026-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0019_lcc_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
