# Generated by Django 4.2.26 on 2026-02-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0019_duenotice_delivery_date_duenotice_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clu',
            old_name='amount_paid',
            new_name='charges',
        ),
        migrations.RenameField(
            model_name='clu',
            old_name='loan_date',
            new_name='emi_paid',
        ),
        migrations.RenameField(
            model_name='clu',
            old_name='fi_address',
            new_name='remarks_for_visit_away_from_cust',
        ),
        migrations.RemoveField(
            model_name='clu',
            name='application_no',
        ),
        migrations.RemoveField(
            model_name='clu',
            name='jointly_visited_emps',
        ),
        migrations.RemoveField(
            model_name='clu',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='clu',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='clu',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='clu',
            name='dpd_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='funder_loan_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='total_amount_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='total_penalty_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
