# Generated by Django 4.2.26 on 2026-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0020_lcc_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('bsp_loading', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('installment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('due_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('emi_due', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'openrepo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loan_no'], name='openrepo_loan_no_646f1d_idx'), models.Index(fields=['vehicle_no'], name='openrepo_vehicle_54276d_idx'), models.Index(fields=['customer_name'], name='openrepo_custome_9ae53d_idx'), models.Index(fields=['branch'], name='openrepo_branch_c6cba8_idx'), models.Index(fields=['company'], name='openrepo_company_cd1d29_idx')],
            },
        ),
    ]
