# Generated by Django 4.2.26 on 2026-04-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0020_rename_amount_paid_clu_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clu',
            name='other_party_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
