# Generated by Django 4.2.26 on 2026-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0021_clu_other_party_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='other_party_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
