# Generated by Django 4.2.26 on 2026-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0021_openrepo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCollectionAllocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_number', models.CharField(db_index=True, max_length=150)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('tl', models.CharField(blank=True, max_length=255, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('tl_employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Sales_Collection_Allocations',
                'indexes': [models.Index(fields=['loan_number'], name='Sales_Colle_loan_nu_2308e6_idx'), models.Index(fields=['manager_employee_id'], name='Sales_Colle_manager_5ee7f4_idx'), models.Index(fields=['tl_employee_id'], name='Sales_Colle_tl_empl_c7a7b7_idx'), models.Index(fields=['employee_id'], name='Sales_Colle_employe_7c528e_idx'), models.Index(fields=['company'], name='Sales_Colle_company_2887d9_idx')],
            },
        ),
    ]
