# Generated by Django 4.2.26 on 2026-08-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0022_salescollectionallocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='coborrower_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='lcc',
            name='guarantor_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
