# Generated by Django 4.2.26 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0022_lcc_other_party_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clu',
            name='other_party_mobile_number',
        ),
        migrations.RemoveField(
            model_name='lcc',
            name='other_party_mobile_number',
        ),
        migrations.AddField(
            model_name='duenotice',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
