# Generated by Django 4.2.26 on 2026-08-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0023_lcc_coborrower_address_lcc_guarantor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
    ]
