# Generated by Django 4.2.26 on 2026-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0023_remove_clu_other_party_mobile_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clu',
            old_name='total_penalty_charges',
            new_name='workshop_outstanding_amt',
        ),
        migrations.AddField(
            model_name='clu',
            name='asset_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='asset_located',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='deceased_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='fir_registered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='insurance_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='other_party_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='reason_for_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='seizure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clu',
            name='trace_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
