# Generated by Django 4.2.26 on 2026-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financehub', '0024_employeemaster_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcc',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
