# Generated by Django 4.2.26 on 2026-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sent_text_message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message_type', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received')], default='Sent', max_length=10)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('interactive', 'Interactive'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp_media/')),
            ],
            options={
                'indexes': [models.Index(fields=['mobile', '-sent_at', '-id'], name='idx_mobile_sent_at'), models.Index(fields=['message_type', 'status'], name='idx_type_status'), models.Index(fields=['-sent_at'], name='idx_sent_at_desc'), models.Index(fields=['message_id'], name='idx_message_id'), models.Index(fields=['job_id', 'status'], name='idx_job_status'), models.Index(fields=['mobile', 'message_type', 'sent_at'], name='idx_mobile_type_sent')],
            },
        ),
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=30, unique=True)),
                ('last_time', models.DateTimeField(db_index=True)),
                ('last_msg', models.TextField(blank=True, null=True)),
                ('last_type', models.CharField(blank=True, max_length=10, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('unread', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['-last_time'], name='messaging_c_last_ti_ca0c93_idx'), models.Index(fields=['mobile'], name='messaging_c_mobile_a749ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=50)),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('excel_file', models.FileField(upload_to='uploads/')),
                ('success_report', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/')),
                ('failed_report', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'started_at'], name='idx_status_started'), models.Index(fields=['job_id'], name='idx_job_id')],
            },
        ),
    ]
