# Generated by Django 4.2.26 on 2026-06-10 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=100)),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=50)),
                ('excel_file', models.CharField(blank=True, default='', max_length=500)),
                ('success_report', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/')),
                ('failed_report', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('current_level', models.CharField(choices=[('ESC0', '🆕 New Case - Unassigned'), ('ESC1', '📞 Level 1 - Agent'), ('ESC2', '⭐ Level 2 - Executive'), ('ESC3', '📊 Level 3 - Manager'), ('ESC4', '👔 Level 4 - Head'), ('ESC5', '🔒 Level 5 - Admin'), ('RESOLVED', '✅ Resolved - Awaiting Closure'), ('CLOSED', '🔒 Closed - Final')], default='ESC0', max_length=20)),
                ('previous_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_at_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved - Pending Closure'), ('Closed', 'Closed - Final'), ('Reopened', 'Reopened')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', '🟢 Low'), ('Medium', '🟡 Medium'), ('High', '🟠 High'), ('Urgent', '🔴 Urgent')], default='Medium', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('reopen_count', models.IntegerField(default=0)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='WhatsApp', max_length=100, null=True)),
                ('source_app', models.CharField(choices=[('app1', 'App 1 - messaging'), ('app2', 'App 2 - messaging2'), ('app3', 'App 3 - splcase')], default='app1', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('sent_text_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('message_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('content_type', models.CharField(blank=True, default='text', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='chat_media/')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.IntegerField(blank=True, help_text='WhatsApp API error code', null=True)),
                ('error_reason', models.TextField(blank=True, help_text='Detailed error reason')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['mobile', '-sent_at'], name='messaging_s_mobile_7c96e0_idx'), models.Index(fields=['-sent_at'], name='messaging_s_sent_at_e218dc_idx'), models.Index(fields=['message_type', 'status'], name='messaging_s_message_43f5c8_idx'), models.Index(fields=['job_id'], name='messaging_s_job_id_fb8e87_idx'), models.Index(fields=['message_id'], name='messaging_s_message_e181f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_msg', models.TextField(blank=True, default='')),
                ('last_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_type', models.CharField(blank=True, default='', max_length=20)),
                ('last_status', models.CharField(blank=True, default='', max_length=500)),
                ('unread', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_level', models.CharField(blank=True, max_length=20, null=True)),
                ('current_level', models.CharField(blank=True, default='ESC1', max_length=20, null=True)),
            ],
            options={
                'ordering': ['-last_time'],
                'indexes': [models.Index(fields=['-last_time', 'unread'], name='messaging_c_last_ti_cec2d0_idx'), models.Index(fields=['mobile'], name='messaging_c_mobile_a749ec_idx'), models.Index(fields=['assigned_to'], name='messaging_c_assigne_476422_idx'), models.Index(fields=['current_level'], name='messaging_c_current_cccc86_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseEscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(max_length=20)),
                ('to_level', models.CharField(max_length=20)),
                ('escalated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_escalation_logs', to='messaging.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
