# Generated by Django 4.2.26 on 2026-04-29 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
