# Generated by Django 4.2.26 on 2026-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatcontact',
            index=models.Index(fields=['mobile'], name='messaging_c_mobile_a749ec_idx'),
        ),
    ]
