# Generated by Django 4.2.26 on 2025-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='failed_report',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='success_report',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
    ]
