# Generated by Django 4.2.26 on 2026-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smswhatsapplog',
            name='sent_text_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
