# Generated by Django 4.2.26 on 2026-06-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('messaging', '0001_initial'),
        ('messaging2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecomment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app1_agent', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_comments', to='messaging.case'),
        ),
        migrations.AddField(
            model_name='caseassignmentlog',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_assignments', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='caseassignmentlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_assignment_logs', to='messaging.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app1_assigned_cases', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app1_cases', to='adminpanel.supportgroup'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_id'], name='messaging_c_case_id_6f7c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['mobile'], name='messaging_c_mobile_c3d4be_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_level'], name='messaging_c_current_1a3524_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='messaging_c_status_31b5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='messaging_c_priorit_60f1a6_idx'),
        ),
    ]
