# Generated by Django 4.2.26 on 2026-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_bulkjob_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='failed_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='success_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
