# Generated by Django 4.2.26 on 2025-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_bulkjob_failed_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smswhatsapplog',
            options={'ordering': ['sent_at', 'id']},
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['mobile'], name='messaging_s_mobile_fafc25_idx'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['sent_text_message'], name='messaging_s_sent_te_2be109_idx'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['sent_at'], name='messaging_s_sent_at_9eb450_idx'),
        ),
    ]
