# Generated by Django 4.2.26 on 2026-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog',
            name='button_response',
            field=models.TextField(blank=True, default='', help_text='Store button click data as JSON'),
        ),
    ]
