# Generated by Django 4.2.26 on 2026-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_bulkjob_failed_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontact',
            name='last_status',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
