# Generated by Django 4.2.26 on 2026-06-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_smswhatsapplog_button_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassignmentlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='messaging.case'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.case'),
        ),
        migrations.AlterField(
            model_name='caseescalationlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='messaging.case'),
        ),
    ]
