# Generated by Django 4.2.26 on 2025-11-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_smswhatsapplog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smswhatsapplog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='smswhatsapplog',
            name='messaging_s_mobile_fafc25_idx',
        ),
        migrations.RemoveIndex(
            model_name='smswhatsapplog',
            name='messaging_s_sent_te_2be109_idx',
        ),
        migrations.RemoveIndex(
            model_name='smswhatsapplog',
            name='messaging_s_sent_at_9eb450_idx',
        ),
    ]
