# Generated by Django 4.2.26 on 2025-12-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_smswhatsapplog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog',
            name='button_reply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog',
            name='interactive_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
