# Generated by Django 4.2.26 on 2026-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_caseassignmentlog_case_alter_casecomment_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ticket_close_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='ticket_open_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
