# Generated by Django 4.2.26 on 2025-12-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_smswhatsapplog_button_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smswhatsapplog',
            name='button_reply',
        ),
        migrations.RemoveField(
            model_name='smswhatsapplog',
            name='interactive_id',
        ),
    ]
