# Generated by Django 6.0.3 on 2026-06-02 10:04


from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_case_caseassignmentlog_casecomment_caseescalationlog_and_more'),
        ('messaging2', '0003_agent_case_caseassignmentlog_casecomment_and_more'),  # ensure Agent exists
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sms_assigned_cases',
                to='messaging2.agent',
            ),
        ),
    ]