# Generated by Django 6.0.3 on 2026-06-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category'),
        ('messaging', '0005_case_ticket_close_message_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app1_subcases', to='adminpanel.subgroup'),
        ),
        migrations.CreateModel(
            name='CaseDescriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_logs', to='messaging.case')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
