# Generated by Django 4.2.26 on 2026-06-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category'),
        ('messaging', '0006_case_subgroup_casedescriptionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app1_categories', to='adminpanel.category'),
        ),
    ]
