# Generated by Django 6.0.3 on 2026-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_add_missing_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='batch_size',
            field=models.IntegerField(default=50),
        ),
    ]
