# Generated by Django 4.2.26 on 2026-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_smswhatsapplog_button_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smswhatsapplog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smswhatsapplog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['mobile', '-sent_at'], name='messaging_s_mobile_7c96e0_idx'),
        ),
    ]
