# Generated by Django 4.2.26 on 2026-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('email', 'email'), ('Whatsapp', 'Whatsapp'), ('socialmedia', 'socialmedia'), ('Physicalvisit', 'Physicalvisit'), ('Notice', 'Notice')], default='WhatsApp', max_length=100, null=True),
        ),
    ]
