# Generated by Django 6.0.3 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_bulkjob_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='completed_batches',
            field=models.IntegerField(default=0),
        ),
    ]
