# Generated by Django 4.2.26 on 2026-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_smswhatsapplog_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
