# Generated by Django 4.2.26 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_smswhatsapplog_job_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smswhatsapplog',
            new_name='idx_mobile_sent_at',
            old_name='messaging_s_mobile_7c96e0_idx',
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['status', 'started_at'], name='idx_status_started'),
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['job_id'], name='idx_job_id'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['message_type', 'status'], name='idx_type_status'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['-sent_at'], name='idx_sent_at_desc'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['message_id'], name='idx_message_id'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['job_id', 'status'], name='idx_job_status'),
        ),
        migrations.AddIndex(
            model_name='smswhatsapplog',
            index=models.Index(fields=['mobile', 'message_type', 'sent_at'], name='idx_mobile_type_sent'),
        ),
    ]
