# Generated by Django 6.0.3 on 2026-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_bulkjob_completed_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
