# Generated by Django 6.0.3 on 2026-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_bulkjob_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smswhatsapplog',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='bulkjob',
            name='total_batches',
            field=models.IntegerField(default=0),
        ),
    ]
