# Generated by Django 4.2.26 on 2026-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_smswhatsapplog_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
