# Generated by Django 4.2.26 on 2026-08-04 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_bulkjob_skipped_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='alt_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
