# Generated by Django 4.2.26 on 2026-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_remove_smswhatsapplog_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
