# Generated by Django 4.2.26 on 2026-06-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_smswhatsapplog_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkjob',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='bulkjob',
            name='completed_batches',
        ),
        migrations.RemoveField(
            model_name='bulkjob',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='bulkjob',
            name='total_batches',
        ),
    ]
