# Generated by Django 4.2.26 on 2026-07-15 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('job_name', models.CharField(max_length=255)),
                ('target_app', models.CharField(help_text='Name of the messaging app', max_length=50)),
                ('template_id', models.CharField(blank=True, help_text='Template ID from forms.py (e.g., 36)', max_length=10, null=True)),
                ('template_name', models.CharField(help_text='Actual template name from WhatsApp (e.g., new_loans_te)', max_length=100)),
                ('template_language', models.CharField(default='en', help_text='Language code (en, te, hi, kn)', max_length=10)),
                ('excel_path', models.CharField(max_length=500)),
                ('batch_size_type', models.CharField(choices=[('custom', 'Custom Size'), ('full', 'Full (All Customers)')], default='custom', max_length=10)),
                ('batch_size', models.IntegerField(default=1000)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('multiple_daily', 'Multiple Times Daily'), ('weekly', 'Weekly'), ('custom_interval', 'Custom Interval (Days)')], default='daily', max_length=20)),
                ('schedule_datetime', models.DateTimeField(help_text='First run date and time, continues daily at same time')),
                ('schedule_times', models.JSONField(blank=True, default=list, help_text='List of times for multiple daily schedules')),
                ('weekly_day', models.IntegerField(blank=True, help_text='Day of week (0=Monday, 6=Sunday)', null=True)),
                ('interval_days', models.IntegerField(blank=True, help_text='Number of days between runs', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Stop scheduling after this date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_batches', models.IntegerField(default=0)),
                ('completed_batches', models.IntegerField(default=0)),
                ('current_batch', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('completed_runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('report_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='batch_app.batchjob')),
            ],
            options={
                'db_table': 'batch_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status', 'next_run_time'], name='batch_jobs_status_dabdda_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['target_app'], name='batch_jobs_target__20ac85_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['template_id'], name='batch_jobs_templat_564a43_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['schedule_type'], name='batch_jobs_schedul_0c496e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['job', 'status'], name='batch_logs_job_id_b196b5_idx'),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['mobile'], name='batch_logs_mobile_7be425_idx'),
        ),
    ]
