# Generated by Django 4.2.26 on 2026-07-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('start_row', models.IntegerField()),
                ('end_row', models.IntegerField()),
                ('total_customers', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='batch_app.batchjob')),
            ],
            options={
                'db_table': 'batch_executions',
                'ordering': ['batch_number'],
                'indexes': [models.Index(fields=['job', 'status'], name='batch_execu_job_id_11c151_idx'), models.Index(fields=['batch_number'], name='batch_execu_batch_n_dbb345_idx')],
            },
        ),
    ]
