# Generated by Django 4.2.26 on 2026-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0002_batchexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='total_runs',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='execution_count',
            field=models.IntegerField(default=0, help_text='Total number of times this job has run'),
        ),
    ]
