# Generated by Django 4.2.26 on 2026-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0003_remove_batchjob_total_runs_batchjob_execution_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='execution_count',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
    ]
