# Generated by Django 4.2.26 on 2026-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0004_remove_batchjob_execution_count_batchjob_total_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='template_name',
            field=models.CharField(blank=True, help_text='Actual template name from WhatsApp (e.g., new_loans_te)', max_length=100, null=True),
        ),
    ]
