# Generated by Django 4.2.26 on 2026-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0005_alter_batchjob_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchexecution',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last time this execution reported progress', null=True),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='progress',
            field=models.IntegerField(default=0, help_text='Number of customers processed in this batch'),
        ),
        migrations.AddField(
            model_name='batchexecution',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='batchexecution',
            index=models.Index(fields=['status', 'started_at'], name='batch_execu_status_d2fa9a_idx'),
        ),
    ]
