# Generated by Django 4.2.26 on 2026-08-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0006_batchexecution_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='batchexecution',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time this execution reported progress', null=True),
        ),
        migrations.AlterField(
            model_name='batchexecution',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('multiple_daily', 'Multiple Times Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_interval', 'Custom Interval (Days)')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_jobs', to='batch_app.notificationtype'),
        ),
    ]
