# Generated by Django 4.2.26 on 2026-08-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0007_notificationtype_alter_batchexecution_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='notification_type',
        ),
    ]
