# Generated by Django 4.2.26 on 2026-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0008_remove_batchjob_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchexecution',
            name='occurrence_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='batchexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('multiple_daily', 'Multiple Times Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_interval', 'Custom Interval (Days)'), ('one_time', 'One Time')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='total_runs',
            field=models.IntegerField(default=0, help_text='Total number of fully completed scheduled occurrences'),
        ),
        migrations.AddIndex(
            model_name='batchexecution',
            index=models.Index(fields=['job', 'occurrence_token', 'batch_number'], name='batch_execu_job_id_49788c_idx'),
        ),
    ]
