# Generated by Django 4.2.26 on 2026-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0009_batchexecution_occurrence_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlog',
            name='due_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batchlog',
            name='emi_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batchlog',
            name='excel_data',
            field=models.JSONField(blank=True, default=dict, help_text='All Excel row data as JSON - includes ALL columns dynamically', null=True),
        ),
        migrations.AddField(
            model_name='batchlog',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchlog',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
