# Generated by Django 6.0.7 on 2026-07-17 12:19

import django.utils.timezone
import portal.models
import portal.services.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('mobile_mask', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='LmsApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=8)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(null=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'lms_api_log',
            },
        ),
        migrations.CreateModel(
            name='PgTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(default=portal.models.new_uuid, max_length=32, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('mobile', portal.services.crypto.EncryptedCharField(max_length=512)),
                ('finance_id', models.CharField(db_index=True, max_length=40)),
                ('agreement_no', models.CharField(blank=True, default='', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lpi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_option', models.CharField(default='total', max_length=20)),
                ('status', models.CharField(db_index=True, default='INITIATED', max_length=30)),
                ('utr', models.CharField(blank=True, default='', max_length=60)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=40)),
                ('lms_receipt_ref', models.CharField(blank=True, default='', max_length=80)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pg_transactions',
            },
        ),
        migrations.CreateModel(
            name='OtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_hash', models.CharField(db_index=True, max_length=64)),
                ('mobile_mask', models.CharField(max_length=20)),
                ('otp_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(default='login', max_length=30)),
                ('attempts', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'otp_log',
                'indexes': [models.Index(fields=['mobile_hash', 'created_at'], name='idx_otp_mobile')],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.CharField(default=portal.models.new_uuid, max_length=32, primary_key=True, serialize=False)),
                ('mobile', portal.services.crypto.EncryptedCharField(max_length=512)),
                ('mobile_mask', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('finance_ids', models.JSONField(default=list)),
                ('login_method', models.CharField(default='mobile_otp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['last_seen_at'], name='idx_sessions_last_seen')],
            },
        ),
    ]
