# Generated by Django 6.0.7 on 2026-07-18 20:10

import django.utils.timezone
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.CharField(default=portal.models.new_uuid, max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'staff_sessions',
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_users',
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
