# Generated by Django 6.0.7 on 2026-07-19 07:56

import portal.services.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_staffsession_staffuser_auditlog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='mobile',
            field=portal.services.crypto.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
