# Generated by Django 4.2.26 on 2026-04-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadHistory',
            new_name='SPLUploadHistory',
        ),
    ]
