# Generated by Django 6.0.3 on 2026-07-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category'),
        ('messaging2', '0009_agent_can_login'),
        ('special_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app3_cases', to='adminpanel.supportgroup'),
        ),
        migrations.AddField(
            model_name='case',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app3_subcases', to='adminpanel.subgroup'),
        ),
        migrations.AddField(
            model_name='case',
            name='ticket_close_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='ticket_open_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smswhatsapplog3',
            name='button_response',
            field=models.TextField(blank=True, default='', help_text='Store button click data as JSON'),
        ),
        migrations.AddField(
            model_name='smswhatsapplog3',
            name='error_code',
            field=models.IntegerField(blank=True, help_text='WhatsApp API error code', null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog3',
            name='error_reason',
            field=models.TextField(blank=True, help_text='Detailed error reason'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app3_assigned_cases', to='messaging2.agent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app3_categories', to='adminpanel.category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='current_level',
            field=models.CharField(choices=[('ESC0', '🆕 New Case - Unassigned'), ('ESC1', '📞 Level 1 - Agent'), ('ESC2', '⭐ Level 2 - Executive'), ('ESC3', '📊 Level 3 - Manager'), ('ESC4', '👔 Level 4 - Head'), ('ESC5', '🔒 Level 5 - Admin'), ('RESOLVED', '✅ Resolved - Awaiting Closure'), ('CLOSED', '🔒 Closed - Final')], default='ESC0', max_length=20),
        ),
        migrations.AlterField(
            model_name='caseassignmentlog',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app3_assignments', to='messaging2.agent'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app3_agent', to='messaging2.agent'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='special_cases.case'),
        ),
        migrations.CreateModel(
            name='CaseDescriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_logs', to='special_cases.case')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
