# Generated by Django 6.0.3 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_cases', '0002_case_group_case_subgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('email', 'email'), ('Whatsapp', 'Whatsapp'), ('socialmedia', 'socialmedia')], default='WhatsApp', max_length=100, null=True),
        ),
    ]
