# Generated by Django 6.0.3 on 2026-06-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging2', '0003_agent_case_caseassignmentlog_casecomment_and_more'),
        ('special_cases', '0002_alter_chatcontact3_last_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('current_level', models.CharField(choices=[('ESC0', '🆕 New Case - Unassigned'), ('ESC1', '📞 Level 1 - Normal Agent'), ('ESC2', '⚖️ Level 2 - Legal Team'), ('ESC3', '⭐ Level 3 - Team Lead'), ('ESC4', '📊 Level 4 - Manager'), ('ESC5', '🔒 Level 5 - Admin'), ('RESOLVED', '✅ Resolved - Awaiting Closure'), ('CLOSED', '🔒 Closed - Final')], default='ESC0', max_length=20)),
                ('previous_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_at_level', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved - Pending Closure'), ('Closed', 'Closed - Final'), ('Reopened', 'Reopened')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', '🟢 Low'), ('Medium', '🟡 Medium'), ('High', '🟠 High'), ('Urgent', '🔴 Urgent')], default='Medium', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('reopen_count', models.IntegerField(default=0)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='WhatsApp', max_length=100, null=True)),
                ('source_app', models.CharField(choices=[('app1', 'App 1 - messaging'), ('app2', 'App 2 - messaging2'), ('app3', 'App 3 - splcase')], default='app3', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(max_length=20)),
                ('to_level', models.CharField(max_length=20)),
                ('escalated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatcontact3',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatcontact3',
            name='assigned_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatcontact3',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatcontact3',
            name='current_level',
            field=models.CharField(blank=True, default='ESC1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smswhatsapplog3',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatcontact3',
            name='last_status',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='chatcontact3',
            index=models.Index(fields=['assigned_to'], name='special_cas_assigne_34dddc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcontact3',
            index=models.Index(fields=['current_level'], name='special_cas_current_fd1fa2_idx'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spl_assigned_cases', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='caseassignmentlog',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spl_assignments', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='caseassignmentlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='special_cases.case'),
        ),
        migrations.AddField(
            model_name='casecomment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spl_case_comments', to='messaging2.agent'),
        ),
        migrations.AddField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spl_comments', to='special_cases.case'),
        ),
        migrations.AddField(
            model_name='caseescalationlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='special_cases.case'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_id'], name='special_cas_case_id_cae438_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['mobile'], name='special_cas_mobile_2ec1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_level'], name='special_cas_current_b99050_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='special_cas_status_23e4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='special_cas_priorit_f6cfe5_idx'),
        ),
    ]
