# Generated by Django 4.2.26 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_cases', '0004_alter_case_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='smswhatsapplog3',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
